### ISSUE TITLE
Problem with undo function (ctrl Z)

### ISSUE THREAD

**Issue by tpbilton** [ajrgodfrey/BrailleR#1]
If you insert anything using the shortcut keys, the ctrl Z function removes only one thing and not everything the shortcut key created (leaves rubbish around). Should be no undo function but windows is giving an undo function.

**Comment by ajrgodfrey** [comment]
OK, this is an issue with WriteR, although it does affect the version being distributed with BrailleR. This issue needs to be moved to the WriteR repository.
