### ISSUE TITLE
non-zero exit status

### ISSUE THREAD

**Issue by mcr999** [ajrgodfrey/BrailleR#12]
Hello Everyone,

When installing the BrailleR package I get the following errors.  Can you please advise?
I'm using a Mac with OSX10.11.6
RStudio 1.0.153 (but I also get the error when only using R.
R version 3.4.1

Thanks in advance.

* installing *source* package ‘gridGraphics’ ...
** package ‘gridGraphics’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in system("convert --version", intern = TRUE, ignore.stderr = TRUE) : 
  error in running command
Error : unable to load R code in package ‘gridGraphics’
ERROR: lazy loading failed for package ‘gridGraphics’
* removing ‘/Users/michael/Library/R/3.4/library/gridGraphics’
Warning in install.packages :
  installation of package ‘gridGraphics’ had non-zero exit status
ERROR: dependency ‘gridGraphics’ is not available for package ‘BrailleR’
* removing ‘/Users/michael/Library/R/3.4/library/BrailleR’
Warning in install.packages :
  installation of package ‘BrailleR’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/hz/9hbt2vmd2991c77c6b7sw11m0000gp/T/Rtmpkqa72t/downloaded_packages’

**Comment by ajrgodfrey** [comment]
Thanks for the helpful description of the issue.

BrailleR depends on the gridGraphics package and because that has failed, the problem has been compounded on to your attempted installation of BrailleR.  I have therefore forwarded your message to the gridGraphics maintainer.

You might try to install gridGraphics manually from CRAN and then re-try the BrailleR installation.

Jonathan

**Comment by pmur002** [comment]
Hi

I have seen this a couple of times on Macs - the gridGraphics install appears to require ImageMagick to be installed (even though this is not required on non-Mac platforms).  I am working on a fix, but in the meantime a workaround is just to install ImageMagick (https://www.imagemagick.org/) on your system.

Hope that works for you

Paul

**Comment by mcr999** [comment]
Perfect!  Solved!

Mike

Michael Chan-Reynolds
Associate Professor
Department of Psychology
Trent University
Peterborough, Ontario, Canada K9J 7B8
Phone: 1 (705) 748 1011 x7534




On Sep 7, 2017, at 5:22 PM, Paul Murrell <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

I have seen this a couple of times on Macs - the gridGraphics install appears to require ImageMagick to be installed (even though this is not required on non-Mac platforms). I am working on a fix, but in the meantime a workaround is just to install ImageMagick (https://www.imagemagick.org/) on your system.

Hope that works for you

Paul
