### ISSUE TITLE
WriteR.pyw does not take a file as an argument

### ISSUE THREAD

**Issue by jooyoungseo** [ajrgodfrey/BrailleR#15]
Hello,

Opposed to the description file, the current version of WriteR.pyw does not allow users to pass a filename as an argument to open in.

I have tested this using Windows command line like below:

python WriteR.pyw test.Rmd

It should create "test.Rmd" in the current working directory and open it with WriteR; however, it does not work as expected.

**Comment by ajrgodfrey** [comment]
This problem needs to be resolved for WriteR outside of R (and therefore BrailleR) before being checked for use inside R.
It needs to be added to the list on the WriteR GitHub.
Jonathan

**Comment by ajrgodfrey** [comment]
Hello,

The command WriteR(“test.Rmd”) for issuing at the R prompt does open a file (perhaps new) called test.Rmd using the version installed with the BrailleR package. I altered a key element of the version installed within the package and it differs from all other versions resident on my machine. This command issues the exact command line  as quoted in the raised issue.

The command line needs to be able to see WriteR.pyw in the  current directory, or in another directory on the system path. Please test that the command line works in that directory without a file being named; if it does then the file may need to exist already. BrailleR::WriteR() creates a file before calling the command line.

**Comment by ajrgodfrey** [comment]
BrailleR users should be using the WriteR() command within the package. For example, WriteR("Testing.Rmd") should open the WriteR app (as long as Python is installed and ready for use) with the file ready to edit. If the file is brand new, then the text will be pretty bland.
