### ISSUE TITLE
There is no assigned keystroke for inserting in-line R chunk in WriteR

### ISSUE THREAD

**Issue by jooyoungseo** [ajrgodfrey/BrailleR#16]
Hello,

I have found that there is no keystroke assigned for inserting in-line R chunk in WriteR editor.

Of course, you can perform by pressing Alt+S, followed by enter key; however, given that you have assigned a keystroke for inserting a block R chunk in WriteR which is Alt+R, followed by I, having a keystroke for in-line R chunk would be so much instrumental for blind R users.

Thank you very much.

**Comment by ajrgodfrey** [comment]
This issue should be on the WriteR GitHub instead of here. Good idea though.
Jonathan

**Comment by ajrgodfrey** [comment]
Hello,

I have assigned the keystroke Alt+C for an in-line command. I do not wish to cause conflicts with pull down menu shortcuts. These se f, e, v, b, o (fOrmat), I, m, s, and h. Alt shortcuts need to be kept at a minimum and only used for the most important things. I have toyed with the idea of having an insertion for a plain code chunk (just opening and closing fences) for example; use of Alt+C for in-line commands stops that from happening for code chunks.

Please continue this thread in the WriteR GitHub if any further discussion is needed.


Thanks of the suggestion
Jonathan

**Comment by jooyoungseo** [comment]
Wow!

 

Fantastic!!

Thank you very much Dr. Godfrey.

 

Sincerely,

 

JooYoung
