### ISSUE TITLE
ROBUSTNESS: Use file.path() instead of paste()

### ISSUE THREAD

**Issue by HenrikBengtsson** [ajrgodfrey/BrailleR#2]
I'd like to suggest to use file.path("a", "b") instead of paste0("a/", "b") for constructing path names.  This is the recommended approach, especially since it makes no assumptions about whether forward or backward slashes should be used.

You can also vectorize, which I see you need in a few places, e.g. file.path("a", c("b1", "b2")).

**Comment by ajrgodfrey** [comment]
Thanks for the solution.
I added the file.path() inside the paste() because the command needs to allow the file.path() to be followed by an optional argument to the function being called.
I hope that works for JYS. I’ll ask him to check via the BlindRUG list.

**Comment by ajrgodfrey** [comment]
needed to add explicit quote marks for the command line to work properly and have success from JYS.

**Comment by HenrikBengtsson** [comment]
I see.  Although JYS email triggered me to look into the code, this issue was not intended to solve his particular problem.  At best, it was intended to minimize the risk for "funny" things happening with path names.
