### ISSUE TITLE
CRAN removal

### ISSUE THREAD

**Issue by MichaelChirico** [ajrgodfrey/BrailleR#25]
Hi @ajrgodfrey, I just saw that you were removed from CRAN. What issues are blocking the package from release there?

Thanks for the great package!

**Comment by ajrgodfrey** [comment]
Hi,
Thanks for the check in.
The VI.ggplot() functionality no longer returns the axis labels properly.

This is on my to-do list once end of semester marking is done with.
Any solutions welcomed. I guess it isn’t all that hard, but I haven’t nutted it out yet.
Jonathan
