### ISSUE TITLE
VI() descriptions for geom_histogram() give really inaccurate numbers of bars 

### ISSUE THREAD

**Issue by boringNectarine0** [ajrgodfrey/BrailleR#35]
VI() for geom_histogram has really weird ideas about numbers of bars. I expect that when sorting by categories it is including any missing category from each bar as a completely missing bar.

eg.
geom_histogram(aes(x, fill=catsOneToSeven), bins=5)

VI() will say that there are 35 vertical bars if there are 7 cats, regardless of whether the colours are included in the bar, and the fact that the default has them stacked and will not leave gaps for missing fill cats.

**Comment by ajrgodfrey** [comment]
Suspect an example is needed for this to provide a test of your solutions.

**Comment by boringNectarine0** [comment]
l<-ggplot(iris) +
  geom_histogram(aes(y=Sepal.Width, fill=Species),bins = 5)
l
VI(l)
In the VI() description it says "The chart is a bar chart containing 15 vertical bars."

**Comment by ajrgodfrey** [comment]
5 bins and 3 species?? Would be wrong of course but is an explanation.

**Comment by boringNectarine0** [comment]
If there was a bar chart with space for 10 bars, but 2 gaps (or 2 bars of 0 height) would we ideally have that said to be 8 bars?

**Comment by ajrgodfrey** [comment]
No.

There is a difference between no observation and a zero observation.

As an example, I’ve been helping an ecology student who has been looking for weta. If she goes into the bush and finds nothing then that is different to her not going into the bush at all. She should have a bar for each bush trip, but of zero height on the bad days.

**Comment by boringNectarine0** [comment]
Is bar height of 0 something worth having in VI() descriptions? By the way, would you have time to reply to my emails? Thanks.

**Comment by ajrgodfrey** [comment]
Yes, zero height bars are important as that is a gap in the data (histogram)  or if categorical data then shows a zero count which might be an anomaly.
On a bus with adequate wifi at the moment. ~30 minutes to spare
J

**Comment by boringNectarine0** [comment]
Another example here is saying that graph is 8 bars

data <- data.frame(
  quarter=c("Q1", "Q1", "Q2", "Q2", "Q3", "Q3", "Q4", "Q4"),
  product=c("A", "B", "A", "B", "A", "B", "A", "B"),
  profit=c(10, 11, 12, 11, 13, 15, 16, 18)
)
VI(ggplot(data, aes(x = quarter, y = profit)) + 
  geom_bar(stat = "identity")
)

because there is a small number of bars the points are described so it does make some sense but as there is no sorting by product A/B this is rather odd.

**Comment by ajrgodfrey** [comment]
I assume you mean the description does not recognise the distinction for product?
The question is what is on the actual graph? Does the description lead you to expect what you see?

N.B. if this example is to feature as a test somewhere, it would be better to use data.frame(expand.grid(Quarter = c(…), Product = c(“A”, “B”)), Count=c(…))
With the first … being the set of quarter names (four only).
You shouldn’t need to switch the two variables in the expand.grid() but choose the one that works for you.

**Comment by boringNectarine0** [comment]
The description makes it seem like there is some sort of deviation between
product shown on the graph when there is not. There are only four plain
bars depicted.

**Comment by ajrgodfrey** [comment]
That’s a big one then.
Definitely should say 4 bars in the description if you see only four in the graph!
