### ISSUE TITLE
Bars in geom_histogram() are always said to be vertical, which they are not

### ISSUE THREAD

**Issue by boringNectarine0** [ajrgodfrey/BrailleR#38]
example:
g<-ggplot(iris) +
  geom_histogram(aes(y=Sepal.Width))

g is a graph of 30 horizontal bars yet VI(g) says "The chart is a bar chart containing 30 VERTICAL bars."

We will need to add recognition of whether y or x is used as the histogram variable to switch between horizontal and vertical

**Comment by ajrgodfrey** [comment]
Sounds good.

**Comment by boringNectarine0** [comment]
Resolved in Pull Request #40
