### ISSUE TITLE
Weird syntax for when coloured fill is used to show groupings

### ISSUE THREAD

**Issue by boringNectarine0** [ajrgodfrey/BrailleR#43]
"X is represented by fill brilliant blue" would make more sense as "X is represented by brilliant blue fill." 
When colour is used the wording "X is represented by colour brilliant blue" which, while not wrong, would also work as "is represented by brilliant blue colour" I will also look into changing the word "represented" to a shorter synonym to save characters.

**Comment by ajrgodfrey** [comment]
Perhaps “shown as” instead of “represented by”

**Comment by boringNectarine0** [comment]
Fixed in PR #41
