### ISSUE TITLE
pdf2html fails

### ISSUE THREAD

**Issue by ucb** [ajrgodfrey/BrailleR#49]
Running the most recent BrailleR from` remotes::install_github("ajrgodfrey/BrailleR", upgrade=TRUE, quiet=TRUE)` and the most recent stable Python 3.10.5, pdf2html fails due to incompatibility with `unicode`

`NameError: name 'unicode' is not defined` thrown off by `File "C:\Program Files\R\R-4.1.0\library\BrailleR\Python\latin2html.py", line 127`

**Comment by ajrgodfrey** [comment]
This was an experiment that didn't attract much love beyond the initial testing.

The main use for any Python in the package (WriteR) is not Py3.10 capable so all development is held back at Py3.8 for the time being. If WriteR cannot be run with Py3.10, then it will need to be split out, and at that point, having any other Python scripts inside BrailleR might become a low value proposition.

I will deprecate pdf2html unless someone shows some desire to fix it to the level of being useful.

N.B. The R installation in your message is 4.1.0; I doubt that matters for this thread.

HTH
Jonathan
