### ISSUE TITLE
Splitting Describe and VI help pages and merging VI help pages

### ISSUE THREAD

**Issue by 1jamesthompson1** [ajrgodfrey/BrailleR#63]
Currently, the help page for Describe and VI feels quite cluttered and the functions serve different purposes.

I think that splitting the help page to Describe and VI would make it clearer and more helpful for users.

Then both pages can actually provide more detailed and better-structured information.

Now there would be two VI help pages and I think that they should be merged to make it consistent with one help page per function

**Comment by ajrgodfrey** [comment]
Go ahead.

From: 1jamesthompson1 ***@***.***>
Sent: Friday, 2 December 2022 5:02 pm
To: ajrgodfrey/BrailleR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ajrgodfrey/BrailleR] Splitting Descrive and VI help pages and merging VI help pages (Issue #63)


Currently, the help page for Describe and VI feels quite cluttered and the functions serve different purposes.

I think that splitting the help page to Describe and VI would make it clearer and more helpful for users.

Then both pages can actually provide more detailed and better-structured information.

Now there would be two VI help pages and I think that they should be merged to make it consistent with one help page per function

-
