### ISSUE TITLE
pkgdown failing to build

### ISSUE THREAD

**Issue by 1jamesthompson1** [ajrgodfrey/BrailleR#70]
Seems to be something about a failure to get the R installation.

> Err:39 https://ppa.launchpadcontent.net/cran/travis/ubuntu jammy Release
>   404  Not Found [IP: 185.125.190.52 443]

**Comment by 1jamesthompson1** [comment]
There seem to be ongoing troubles with this [issue](https://github.com/r-lib/actions/issues/559)

It can be fixed with a bit of work. IT is odd that it has only popped up now.

There are a few suggestions that I can try.

**Comment by 1jamesthompson1** [comment]
Success! 

It seems like #72 has fixed the problems and can carry on with actual R work now.

**Comment by ajrgodfrey** [comment]
Phew!
