### ISSUE TITLE
Add VI and describe information to SVG webpage?

### ISSUE THREAD

**Issue by 1jamesthompson1** [ajrgodfrey/BrailleR#80]
Would there be interest in adding the VI and describe printout to the BrowseSVG webpage.

This could be done with keyboard shortcuts to let the user quickly access the text when explaining the graph.

**Comment by ajrgodfrey** [comment]
Maybe.

Putting it into the landing page under the instructions could be done. Screen readers already have hot keys in web pages for headings etc. Putting the VI() under a heading of "Full description" or some such and then the Describe() stuff under another heading for "General overview" might help.
