### ISSUE TITLE
Move the whiskers templates from html to md

### ISSUE THREAD

**Issue by 1jamesthompson1** [ajrgodfrey/BrailleR#81]
In recent dev work, I have made both `BrowseSVG()` and `ViewSVG()` use whiskers templates.

In doing so I moved ViewSVG away from .md in favor of templates being in straight HTML.

Looking at some of the other issues #80  it may be beneficial or not to use .md for the web pages so that they can look better without as much work. On the other hand, it might be more difficult if the changes suggested here #80 go through.

**Comment by ajrgodfrey** [comment]
Let's discuss this in the new year.
