### ISSUE TITLE
Summarise and fleshout SVGs and XMLs of "bar" and "line" type ggplots geoms

### ISSUE THREAD

**Issue by 1jamesthompson1** [ajrgodfrey/BrailleR#82]
Currently, the information is there.

You can step through and find out what bars or lines there are. However, the information isn't filtered or summarised in any way. Meaning that it could be quite hard for a user to actually explore the graph.

Within the lines type, there could be a better job of connecting lines together to make longer lines and thus fewer lines need to be displayed and read.

The bar types are alright but there is no cap on the number of bars that can be displayed.

**Comment by ajrgodfrey** [comment]
Yes, but part of this issue comes from the greater ability to get more detail from a ggplot than from a base graphic. E.g. histograms have 30 bars in ggplot, but usually 8-15 in base graphics.
