### ISSUE TITLE
Add SVG and XML support for multiple layers

### ISSUE THREAD

**Issue by 1jamesthompson1** [ajrgodfrey/BrailleR#83]
The system is set up at the moment to just assume all layers are the same and act accordingly.

Having a way that each layer can be toggled on and off or "stepped" through would be good in the exploration of the graph.

To be able to do this we will probably need to access more information potentially the build object meaning that we might need to be passed the origin graph object as opposed to looking at the displayed graphic.

**Comment by ajrgodfrey** [comment]
OK, add this to the agenda for the next verbal update in the new year.
