### ISSUE TITLE
Offer for side-by-side development

### ISSUE THREAD

**Issue by timcdlucas** [ajrgodfrey/BrailleR#9]
Hi,

Just thought I'd offer my time for side-by-side development as requested in the README. I'm based in the UK, so geography and time-differences are an issue. But if we could work out suitable times and something like a skype call with screenshare, I'd love to help develop the package further.

My email address is timcdlucas@gmail.com. Let me know if you want to try and organise something.

**Comment by ajrgodfrey** [comment]
Thanks for the idea.
I get most of my work done during my afternoons so taking up your offer is going to be a challenge.

I guess I’m really looking for contributors to bounce ideas back and forth. Are you an R user? Perhaps make contact using my work address with more information about yourself and let’s look for a useful way to move forwards.

Cheers,
Jonathan
